CREATE TABLE [dbo].[EMPLOYEESTABLE] (
    [ID]          INT NOT NULL,
    [FIRSTNAME]   NVARCHAR (50) NOT NULL,
    [LASTNAME]    NVARCHAR (50) NULL,
    [GENDER]      NVARCHAR (50) NULL,
    [SALARY]      NVARCHAR (50) NULL,
    [DATEOFBIRTH] DATE          NULL,
    CONSTRAINT [PK_EMPLOYEESTABLE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

