//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO.NET_CONNECTION_SQLEXPRESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumenDeCosas
    {
        public string code { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
    }
}
