//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDataAccessTwo
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        public string code { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public decimal annualSalary { get; set; }
        public string dateOfBirth { get; set; }
    }
}
